apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: g29dmpszq-go 
  janus-idp.io/tekton: g29dmpszq-go
  backstage.io/kubernetes-id: g29dmpszq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g29dmpszq-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml