apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: g29dmpszq-go-gitops
  description: This is GitOps manifest for g29dmpszq-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=g29dmpszq-go
    backstage.io/kubernetes-id: g29dmpszq-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: g29dmpszq-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:g29dmpszq-go
